spring:
  datasource:
    url: jdbc:h2:file:./catalog_film_db
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

app:
  admin:
    username: admin
    password: admin
    email: admin@mail.ru
